# REUSE configuration (https://reuse.software) — machine-readable copyright and
# licensing for every file in the repository, without having to add an SPDX
# header to each one. This makes the project REUSE-compliant (one catch-all rule:
# everything is Apache-2.0, copyright Maks Tonkonozhenko) and keeps binary assets
# and generated files covered too.
version = 1

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Maks Tonkonozhenko (https://github.com/tonkonozhenko-mi)"
SPDX-License-Identifier = "Apache-2.0"
