"""Machine-written code answers questions about the machine.

Every generator stamps its output with the same sentence — "Code generated …
DO NOT EDIT." — and until now the app read that sentence as ordinary source. On
a repo of Go services, "Where is the gRPC API defined?" was answered with three
protobuf stubs instead of the .proto file a person actually wrote (external eval,
online-boutique, 2026-07-13).

The rule is deliberately narrow: the marker must be in a comment, and in the
first few lines. Prose in a README that says "do not edit this section" is not a
generator's signature, and neither is the phrase turning up halfway down a file.
"""

from app.core.domain.source_files import is_generated_source

# The real header of a protoc-gen-go-grpc stub.
GRPC_STUB = """// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0

package demo

import grpc "google.golang.org/grpc"
"""


def test_a_protobuf_stub_is_recognised_as_machine_written():
    assert is_generated_source(GRPC_STUB)


def test_a_python_generated_header_is_recognised():
    assert is_generated_source("# @generated by datamodel-codegen\n\nclass Order:\n    pass\n")


def test_prose_about_not_editing_is_not_a_generator_signature():
    readme = (
        "# Configuration\n\n"
        "Please do not edit this section by hand; it is generated from the schema.\n"
    )
    assert not is_generated_source(readme)


def test_the_marker_must_be_in_the_header_not_buried_in_the_file():
    body = "\n".join(["def step():", "    return 1"] * 25)
    assert not is_generated_source(f"{body}\n// Code generated later on\n")


def test_a_minified_bundle_is_still_refused():
    assert is_generated_source("var a=1;" + "x" * 3000 + "\n")


def test_ordinary_source_is_left_alone():
    assert not is_generated_source("package main\n\nfunc main() {\n\tprintln(\"hi\")\n}\n")
