from dataclasses import dataclass, field


@dataclass(frozen=True)
class ProjectTodo:
    """A single TODO-style marker found verbatim in a project file."""

    file: str
    line: int
    marker: str  # one of the recognised marker words, e.g. FIXME or HACK
    text: str


@dataclass(frozen=True)
class ProjectTodos:
    """Deterministic inventory of TODO-style markers across the project.

    These are read directly from file contents — never generated by a model —
    so the list is always faithful to what is actually written in the code.
    """

    total: int = 0
    truncated: bool = False
    items: list[ProjectTodo] = field(default_factory=list)
